idci_exporter:
    api_route: "/api/{entity_reference}.{_format}"
    entities:
        partner:
            class: "IDCI\\Bundle\\PartnerBundle\\Entity\\Partner"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

        partner_social_link:
            class: "IDCI\\Bundle\\PartnerBundle\\Entity\\SocialLink"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

        partner_category:
            class: "IDCI\\Bundle\\PartnerBundle\\Entity\\Category"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

        partner_location:
            class: "IDCI\\Bundle\\PartnerBundle\\Entity\\Location"
            formats:
                jsonp:
                    transformer:
#                        service: "idci_exporter.transformer_twig"
                        options:
#                            template_path:
                            template_name_format: "export.json.twig"

